### ISSUE TITLE
Help on exporting processed data sets from R

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/NORDCAN#20]
Some of the NORDCAN R-users are not that familiar with R. For quality assurance and for checking of data they might want to export the processed cancer case dataset and the processed cancer death dataset to another system. If now knowing R, it is not that simple for all users to know how to do this. 

Could we include some help in the nordcan.R on how to export data to different files? I think the most common files users would want to export to is:
* csv
* dta
* sas

Just getting the commands to do this would be sufficient help. They could either be in the script itself or they could be in the help-file (like a ?helpexport or something like that). I don't know what would be best.

**Comment by HuidongTian** [comment]
To include the feature of exporting data as **.dta** & **.sas** format, we need to include another R package (**haven**), which we have decided not to include that package in the beginning. we can:

1. include that package.  or
2. export processed data to  csv format only, because most of statistical softwares will accept csv format. 

tell me your opinion.

**Comment by CotterpinDoozer** [comment]
csv is fine for now! No need to include haven.

**Comment by BjarteAAGNES** [comment]
Just a comment: even if we do not include libraries for exporting to other formats **it is possible to explain how the user can install and use a package like haven.**

**Comment by CotterpinDoozer** [comment]
True. So we could provide them with code for exporting to csv and a help-file for other exports.

**Comment by HuidongTian** [comment]
Add a block of [codes ](https://github.com/CancerRegistryOfNorway/NORDCAN/blob/master/nordcan_participant_instructions/nordcan.R#L134-L138) for exporting undefined records as .csv file.

**Comment by HuidongTian** [comment]
The exported data are all in .csv format, including the .zip file.
