### ISSUE TITLE
return Sasha to group after UF has left  

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#24]
return Sasha to group after UF has left

**Comment by BjarteAAGNES** [comment]
due 1 June or before

**Comment by CotterpinDoozer** [comment]
Bjarte: has UF left now? Can you return Sasha?

**Comment by BjarteAAGNES** [comment]
No. But close. Early August. BTW as STAU are on leaf I dont think any  changes can be done to users,
