### ISSUE TITLE
filenames and paths

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#25]
ref https://cancerregistr-hhd6843.slack.com/archives/C01GD3P45TJ/p1652180229830189

Either the spec must be specific about a norm for naming of files and paths ( "a-z0-1_" etc ) and validate user imput, or preferably we provide this functionality then properly tested for filename/dirs with spaces and "non-ascii" letter characters.

The Stata .do files written by R must be UTF-8. Thus, if "non-ascii" letter characters are used in paths written to the .do file R must write UTF-8, or the .do file must be translated to UTF-8, before calling Stata.

(spaces in filename/path in cmd shell is left out here)

**Comment by BjarteAAGNES** [comment]
Since I in email said  "Hi, I will update issue status today.":

We fixed some issues (19 Oct), but the survival statistics part need some additional testing.  I might be able to test the Stata part independently of the R/Nordcan code before holidays. (I will problably have holidays first week of January. ) The fix will be implemented in January (sceduled for week 2 @HuidongTian ?)  (ref: emails SLA: RE: nordcan.R survival - fix for filepath)

**Comment by BjarteAAGNES** [comment]
-----Original Appointment-----
From: Bjarte Aagnes 
Sent: tirsdag 13. desember 2022 13:56
To: Bjarte Aagnes; Huidong Tian
Subject: https://github.com/CancerRegistryOfNorway/NORDCAN/issues/25
When: fredag 13. januar 2023 10:00-13:00 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
Where: Microsoft Teams Meeting

https://github.com/CancerRegistryOfNorway/NORDCAN/issues/25

**Comment by BjarteAAGNES** [comment]
The test today, using the **19 Oct version of  extract_define_survival_data.ado** did run without error, also without additional changes to survival_statistics.ado , which is a odd given, the comment above.  This issue seems to be solved, and will be closed after final testing and a push to gitlab by me.  

![image](https://user-images.githubusercontent.com/18100532/214093617-2a15cc37-4d47-4caf-91c6-3a6193ee00d6.png)

**Comment by CotterpinDoozer** [comment]
Huidong will test using Chinese characters.

**Comment by HuidongTian** [comment]
I tested using a directory contains Norwegian, space and Chinese characters. Unfortunately, it didn't pass the test. 

![Capture 2](https://user-images.githubusercontent.com/60390550/215490328-ecc197de-c669-4c8e-9044-dbfb957dfa60.PNG)

**Comment by HuidongTian** [comment]
One possible bug is: nordcansurvival's R part using package data.table to save dataset for further analysis by STATA.  The function "fwrite" convert the file path using "enc2native", which will convert the path to native encoding, and my computer's native encoding is "Latin1" which can not encode some characters. One solution could change the "enc2native" to "enc2utf8", however, that will change the package data.table, alternatively we can change the computer's native encoding to UTF-8, but I didn't find an easy way that all users can easily use. Another solution is:  the lastest version R (4.2.1) supports UTF-8 encoding as native encoding, [R]{https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/}, so I plan to upgrade my R (with the help from IT department) to check how this issue going.

**Comment by BjarteAAGNES** [comment]
`inst/stata/ado/extract_define_survival_data.ado` commited after testing:

https://gitlab.kreftregisteret.no/nordcan/nordcansurvival/-/commit/411991ae420f4a793470285f32b04f67e17d5553

Added quotes for paths. 

In addition: formatting

**Comment by BjarteAAGNES** [comment]
The spaces in filename is fixed.  This issue will be closed. A new issue for "special chars" in paths will  made.
