### ISSUE TITLE
proposal new agegroups /weights for 3-level age groups

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#30]
For analyses using 10-year calendar periods the weights for the five-level age groups above were collapsed to three levels by: 
combining groups into groups with similar weights.

Below, the original aggregation is on the left. This combine age groups 1-2, 3, 4-5 into "A", "B" ,"C".   

The new aggregation at right.  For ICSS 1 the old and new aggregation give identical age groups for 3-level age groups:

    1. ICSS 1 Elderly. Most sites and summary groups: 

    A. 0–49  (12), 
    A. 50–59 (17),  [29] A 0-59
    B. 60–69 (27),  [27] B 60–69  
    C. 70–79 (29),  [44] C 70-89
    C. 80–89 (15)

    2. ICSS 2.  Little age dependency:
  
    i. Bone: 

    A. 0–29   (7), 
    A. 30–39 (13), 
    B. 40–49 (16), [36] A 0-49
    C. 50–69 (41), [41] B 50-69 
    C. 70–89 (23)  [23] C 70-89 

    ii. Melanoma, cervix, brain, thyroid, soft tissue: 

    A. 0–49 (36),   [36] A 0–49  
    A. 50–59 (19), 
    B. 60–69 (22),  [41] B 50-69
    C. 70–79 (16),  [23] C 70-89
    C. 80–89 (7)

    3. ICSS 3. Young adults. 

    i. Testis, Hodgkin lymphoma: 

    A. 0–29  (31),  [31] A 0–29   
    A. 30–39 (21), 
    B. 40–49 (13),  [34] B 30-49
    C. 50–69 (20),   
    C. 70–89 (15)   [35] C 50-89

    ii. Acute leukemia: 

    A. 0–29 (31),   [31] A 0-29 
    A. 30–49 (34),  [34] B 30-49
    B. 50–69 (20), 
    C. 70–79 (10), 
    C. 80–89 (5)    [35] C 50-89

**Comment by CotterpinDoozer** [comment]
Looks good!
