### ISSUE TITLE
proposed text WARNING ICCS In Engholm et al (2010)

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#31]
WARNING
In Engholm et al (2010), "ICSS 1 Elderly" was named "ICSS 3 Elderly" and  "ICSS 3 Elderly" named "ICSS 1 Young adults" in contrast to the original ICSS terms used in current version of NORDCAN.

**Comment by CotterpinDoozer** [comment]
I asked Gerda about this in June 2022. The original paper defining the ICCS-standards is this article: https://www.sciencedirect.com/science/article/pii/S0959804904005283. 
Corazziari I, Quinn M, Capocaccia R. Standard cancer patient population for 
age standardising survival ratios. Eur J Cancer. 2004 Oct;40(15):2307-16. doi:
10.1016/j.ejca.2004.07.002. PMID: 15454257.

Gerda writes as an explanation to why the NORDCAN 1.0-tables were different from the article by Engholm et.al (2010): 
"Some years ago I was critizised for not sticking to the original order, so I changed it in the old NORDCAN platform."

I suggest we write the following: 

WARNING: 
In Engholm et al (2010), "ICSS 1 Elderly" was named "ICSS 3 Elderly" and "ICSS 3 Young adults" named "ICSS 1 Young adults" in contrast to the original ICSS terms used in Corazziari et al (2004). In NORDCAN we use the naming from the original article: ICCS 1 Elderly (Standard 1), ICSS 2 Little age dependency (Standard 2) and ICSS 3 Young adults (Standard 3).
