### ISSUE TITLE
test github Project 

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#33]
MWE github [Projects](https://github.com/orgs/CancerRegistryOfNorway/projects/3/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%2C%22Repository%22%2C%22Milestone%22%2C%22Linked+pull+requests%22%5D)

**Comment by CotterpinDoozer** [comment]
Perfect!
