### ISSUE TITLE
Licensing of NORDCAN packages

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/NORDCAN#5]
We need to discuss the licensing of the NORDCAN-package. It is in good cancer registry-spirit to share the work we have done freely, and this is also in accordance with our principles of transparency and reusability.

Having no license is probably not a good idea, ref. [https://choosealicense.com/no-permission/ ](url)

Normally, the MIT-license is a good choice. This does not hinder commercial use, but we don't think this is a big issue, since this is probably not a product worth selling to anyone - the potential users are cancer registries that can get it for free. However: The suggested MIT cannot cover our example data and provided Stata commands.

[https://opensource.org/licenses/MIT](url)
 
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), **to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software**, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 
We could maybe go for something like this: [https://creativecommons.org/licenses/by-sa/4.0/](url), but we need to discuss this further.

**Comment by CotterpinDoozer** [comment]
Input from @BjarteAAGNES: for the R-modules, MIT-license would probably be sufficient, but for Stata we need something else, since we here have a synthetic dataset which currently is strictly prohibited for use by our legal adviser. 

Siri will discuss with the CRN legal adviser, but it might be that we have to publish the packages without test-data. Is that possible, Bjarte? Or is that a big change to the Stata survival-part?

**Comment by BjarteAAGNES** [comment]
1) ref discussion: It should be possible to have more than one licence, also within a package.  So, MIT for all code except X,Y,Z. But, this is a major issue first it the code is distributed/published on a public repo.

2) The example data has a readme file with the current legal statement. 
(This particular data may be replaced with some other in the future  - before publishing on a public repo)

3) The Stata part will ALWAYS have programs written by others, like the stnet.ado and any copyright are following those programs.  

Also, https://github.com/CancerRegistryOfNorway/nordcansurvival/issues/19

**Comment by CotterpinDoozer** [comment]
Lisence is published. We close this task now.
