### ISSUE TITLE
nordcan_call_for_data_manual.html SURVIVAL AGE GROUPS

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/NORDCAN#7]
### description of calculated age groups included in call for data manual

In the **nordcan_call_for_data_manual.html** included in the nordcan_9.0.beta2_participant_instructions, the following table is included, despite not being part of any call for data

( only _documenting_ age groups calculated from "age" )

https://github.com/CancerRegistryOfNorway/NORDCAN/wiki/Specification-Age-groups

**Comment by CotterpinDoozer** [comment]
Is the issue that you DON'T want that table to be included in the nordcan_call_for_data_manual?

**Comment by BjarteAAGNES** [comment]
Yes, this it is not information for how to provide data. This is description of something made by the system during the process.

**Comment by CotterpinDoozer** [comment]
Ok, I will let Joonas know that this should be removed when making the html-file.

**Comment by CotterpinDoozer** [comment]
Joonas: can you remove age groups from the html nordcan_call_for_data_manual? This is  handled within the R-modules, and the user does not have to care about this.
